# Generated by Django 3.2.16 on 2023-01-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='area',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='price',
            field=models.IntegerField(),
        ),
    ]
